instance = "# Instance: {instance}"
path = "## {source} -> {destination}"
promote_images = "* Promote images: {targets}"
promote_config_maps = "* Promote config maps: {targets}"
promote_secrets = "* Promote secrets: {targets}"
